# Generated by Django 5.2.13 on 2026-04-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_profile',
            field=models.TextField(blank=True, null=True),
        ),
    ]
