# Generated by Django 5.2.13 on 2026-04-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_full_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='crawl_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('running', 'Running'), ('expired', 'Expired')], default='waiting', max_length=20),
        ),
    ]
