# Generated by Django 5.2.13 on 2026-04-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0004_profile_linkedin_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preference",
            name="crawl_url",
            field=models.URLField(blank=True, help_text="Filled by Admin", null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="full_profile",
            field=models.TextField(blank=True, help_text="Filled by Admin", null=True),
        ),
    ]
