# Generated by Django 5.2.13 on 2026-05-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0008_preference_crawl_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="suggested_full_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
