# Generated by Django 5.2.13 on 2026-05-01 17:15

from django.db import migrations, models


def grandfather_existing_profiles(apps, schema_editor):
    Profile = apps.get_model("profiles", "Profile")
    Profile.objects.filter(full_profile__isnull=False).exclude(full_profile="").update(
        linkedin_quality_ok=True,
        linkedin_quality_reason="grandfathered from pre-ingest data",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0009_profile_suggested_full_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="linkedin_ingested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="linkedin_quality_ok",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="linkedin_quality_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="profile",
            name="linkedin_raw",
            field=models.TextField(
                blank=True,
                help_text="Raw LinkedIn paste (audit / re-run source)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="open_to_work",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="profile",
            name="full_profile",
            field=models.TextField(
                blank=True, help_text="LLM-cleaned LinkedIn content", null=True
            ),
        ),
        migrations.RunPython(
            grandfather_existing_profiles, reverse_code=migrations.RunPython.noop
        ),
    ]
