# Generated by Django 5.2.13 on 2026-05-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0010_profile_linkedin_ingested_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
