# Generated by Django 5.2.13 on 2026-05-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0012_alter_preference_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="whitelist",
            field=models.BooleanField(
                default=False,
                help_text="Bypass plan limits (preference cap, future crawl caps).",
            ),
        ),
    ]
