# Generated by Django 5.2.14 on 2026-05-11 08:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0015_preference_crawl_urls"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="preference",
            index=models.Index(fields=["status"], name="profiles_pr_status_2bc3c9_idx"),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["linkedin_quality_ok"], name="profiles_pr_linkedi_5f4b61_idx"
            ),
        ),
    ]
