# Generated by Django 5.2.13 on 2026-05-04 15:24

import django.db.models.deletion
from django.db import migrations, models


def backfill_amount_paid(apps, schema_editor):
    Subscription = apps.get_model("billing", "Subscription")
    for sub in Subscription.objects.select_related("plan").filter(amount_paid=0):
        if sub.plan_id:
            sub.amount_paid = sub.plan.price
            sub.save(update_fields=["amount_paid"])


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="amount_paid",
            field=models.PositiveIntegerField(
                default=0, help_text="IDR actually paid (post-discount, post-credit)"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="replaces",
            field=models.ForeignKey(
                blank=True,
                help_text="Old subscription this upgrade replaces.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replaced_by_subs",
                to="billing.subscription",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACTIVE", "Active"),
                    ("EXPIRED", "Expired"),
                    ("CANCELLED", "Cancelled"),
                    ("REPLACED", "Replaced"),
                ],
                default="PENDING",
                max_length=16,
            ),
        ),
        migrations.RunPython(backfill_amount_paid, migrations.RunPython.noop),
    ]
