# Generated by Django 5.2.14 on 2026-05-11 08:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0002_subscription_amount_paid_subscription_replaces_and_more"),
        ("profiles", "0016_preference_profiles_pr_status_2bc3c9_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["status", "expires_at"], name="billing_sub_status_d93e7f_idx"
            ),
        ),
    ]
