# Generated by Django 5.2.14 on 2026-07-15 02:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0003_subscription_billing_sub_status_d93e7f_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="duration_days",
            field=models.PositiveSmallIntegerField(
                default=30,
                help_text="Subscription length in days.",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
