# Generated by Django 5.2.13 on 2026-04-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="url",
            field=models.URLField(unique=True),
        ),
    ]
