# Generated by Django 5.2.13 on 2026-04-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0002_alter_job_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="source",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
