# Generated by Django 5.2.13 on 2026-04-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0003_job_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="company",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
