# Generated by Django 5.2.14 on 2026-05-17 13:25

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

SEED_LABELS = ["Indeed default", "Jobstreet default"]


def seed_defaults(apps, schema_editor):
    CrawlHealthTarget = apps.get_model("jobs", "CrawlHealthTarget")
    seeds = [
        {
            "label": "Indeed default",
            "source": "indeed",
            "url": "https://id.indeed.com/jobs?q=mobile+developer",
            "is_active": True,
        },
        {
            "label": "Jobstreet default",
            "source": "jobstreet",
            "url": "https://id.jobstreet.com/mobile-developer-jobs",
            "is_active": True,
        },
    ]
    for row in seeds:
        CrawlHealthTarget.objects.get_or_create(label=row["label"], defaults=row)


def unseed_defaults(apps, schema_editor):
    CrawlHealthTarget = apps.get_model("jobs", "CrawlHealthTarget")
    CrawlHealthTarget.objects.filter(label__in=SEED_LABELS).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0005_schedule_crawl_health_check"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CrawlHealthTarget",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.models.make_object_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(max_length=120)),
                (
                    "source",
                    models.CharField(
                        choices=[("indeed", "Indeed"), ("jobstreet", "Jobstreet")],
                        max_length=20,
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["label"],
            },
        ),
        migrations.RunPython(seed_defaults, unseed_defaults),
    ]
