# Generated by Django 5.2.14 on 2026-06-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0006_crawlhealthtarget"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crawlhealthtarget",
            name="source",
            field=models.CharField(
                choices=[
                    ("indeed", "Indeed"),
                    ("jobstreet", "Jobstreet"),
                    ("glints", "Glints"),
                ],
                max_length=20,
            ),
        ),
    ]
