# Generated by Django 5.2.14 on 2026-06-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0007_alter_crawlhealthtarget_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crawlhealthtarget",
            name="source",
            field=models.CharField(
                choices=[("indeed", "Indeed"), ("jobstreet", "Jobstreet")],
                max_length=20,
            ),
        ),
    ]
