# Generated by Django 5.2.14 on 2026-06-03 01:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0009_delete_glints_jobs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crawlhealthtarget",
            name="source",
            field=models.CharField(
                choices=[
                    ("indeed", "Indeed"),
                    ("jobstreet", "Jobstreet"),
                    ("linkedin", "LinkedIn"),
                ],
                max_length=20,
            ),
        ),
    ]
