# Generated by Django 5.2.14 on 2026-06-03 03:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0010_alter_crawlhealthtarget_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="hard_skills",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="job",
            name="soft_skills",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
