# Generated by Django 5.2.14 on 2026-07-01 00:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0012_seed_linkedin_crawl_health"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crawlhealthtarget",
            name="source",
            field=models.CharField(
                choices=[
                    ("indeed", "Indeed"),
                    ("jobstreet", "Jobstreet"),
                    ("linkedin", "LinkedIn"),
                    ("dealls", "Dealls"),
                ],
                max_length=20,
            ),
        ),
    ]
