# Generated by Django 5.2.14 on 2026-09-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0014_seed_dealls_crawl_health"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crawlhealthtarget",
            name="source",
            field=models.CharField(
                choices=[
                    ("indeed", "Indeed"),
                    ("jobstreet", "Jobstreet"),
                    ("linkedin", "LinkedIn"),
                    ("dealls", "Dealls"),
                    ("kalibrr", "Kalibrr"),
                    ("kitalulus", "Kitalulus"),
                    ("karirhub", "Karirhub"),
                ],
                max_length=20,
            ),
        ),
    ]
