# Generated by Django 5.2.13 on 2026-04-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("seen", "Seen"),
                    ("applied", "Applied"),
                    ("rejected", "Rejected"),
                    ("accepted", "Accepted"),
                ],
                default="new",
                max_length=20,
            ),
        ),
    ]
