# Generated by Django 5.2.13 on 2026-04-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0002_assessment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="verdict",
            field=models.TextField(blank=True, help_text="Verdict by AI", null=True),
        ),
    ]
