# Generated by Django 5.2.13 on 2026-04-30 10:45

from django.conf import settings
from django.db import migrations, models


def dedupe_assessments(apps, schema_editor):
    Assessment = apps.get_model("assessment", "Assessment")
    seen = set()
    dupe_ids = []
    for row in Assessment.objects.order_by("created_on").values(
        "id", "job_id", "preference_id"
    ):
        key = (row["job_id"], row["preference_id"])
        if key in seen:
            dupe_ids.append(row["id"])
        else:
            seen.add(key)
    if dupe_ids:
        Assessment.objects.filter(id__in=dupe_ids).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0004_schedule_crawl_running_preferences"),
        ("jobs", "0003_job_source"),
        ("profiles", "0008_preference_crawl_source"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(dedupe_assessments, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="assessment",
            constraint=models.UniqueConstraint(
                fields=("job", "preference"),
                name="unique_assessment_per_job_preference",
            ),
        ),
    ]
