# Generated by Django 5.2.13 on 2026-05-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0005_assessment_unique_assessment_per_job_preference"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="is_relevant",
            field=models.BooleanField(default=True),
        ),
    ]
