/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PreferencesRouteImport } from './routes/preferences'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AssessmentsRouteImport } from './routes/assessments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PreferencesIndexRouteImport } from './routes/preferences.index'
import { Route as AssessmentsIndexRouteImport } from './routes/assessments.index'
import { Route as PreferencesIdRouteImport } from './routes/preferences.$id'
import { Route as AssessmentsIdRouteImport } from './routes/assessments.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesRoute = PreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsRoute = AssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesIndexRoute = PreferencesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PreferencesRoute,
} as any)
const AssessmentsIndexRoute = AssessmentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AssessmentsRoute,
} as any)
const PreferencesIdRoute = PreferencesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PreferencesRoute,
} as any)
const AssessmentsIdRoute = AssessmentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AssessmentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessments': typeof AssessmentsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/preferences': typeof PreferencesRouteWithChildren
  '/signup': typeof SignupRoute
  '/assessments/$id': typeof AssessmentsIdRoute
  '/preferences/$id': typeof PreferencesIdRoute
  '/assessments/': typeof AssessmentsIndexRoute
  '/preferences/': typeof PreferencesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/assessments/$id': typeof AssessmentsIdRoute
  '/preferences/$id': typeof PreferencesIdRoute
  '/assessments': typeof AssessmentsIndexRoute
  '/preferences': typeof PreferencesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assessments': typeof AssessmentsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/preferences': typeof PreferencesRouteWithChildren
  '/signup': typeof SignupRoute
  '/assessments/$id': typeof AssessmentsIdRoute
  '/preferences/$id': typeof PreferencesIdRoute
  '/assessments/': typeof AssessmentsIndexRoute
  '/preferences/': typeof PreferencesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessments'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/preferences'
    | '/signup'
    | '/assessments/$id'
    | '/preferences/$id'
    | '/assessments/'
    | '/preferences/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/assessments/$id'
    | '/preferences/$id'
    | '/assessments'
    | '/preferences'
  id:
    | '__root__'
    | '/'
    | '/assessments'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/preferences'
    | '/signup'
    | '/assessments/$id'
    | '/preferences/$id'
    | '/assessments/'
    | '/preferences/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessmentsRoute: typeof AssessmentsRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PreferencesRoute: typeof PreferencesRouteWithChildren
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments': {
      id: '/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences/': {
      id: '/preferences/'
      path: '/'
      fullPath: '/preferences/'
      preLoaderRoute: typeof PreferencesIndexRouteImport
      parentRoute: typeof PreferencesRoute
    }
    '/assessments/': {
      id: '/assessments/'
      path: '/'
      fullPath: '/assessments/'
      preLoaderRoute: typeof AssessmentsIndexRouteImport
      parentRoute: typeof AssessmentsRoute
    }
    '/preferences/$id': {
      id: '/preferences/$id'
      path: '/$id'
      fullPath: '/preferences/$id'
      preLoaderRoute: typeof PreferencesIdRouteImport
      parentRoute: typeof PreferencesRoute
    }
    '/assessments/$id': {
      id: '/assessments/$id'
      path: '/$id'
      fullPath: '/assessments/$id'
      preLoaderRoute: typeof AssessmentsIdRouteImport
      parentRoute: typeof AssessmentsRoute
    }
  }
}

interface AssessmentsRouteChildren {
  AssessmentsIdRoute: typeof AssessmentsIdRoute
  AssessmentsIndexRoute: typeof AssessmentsIndexRoute
}

const AssessmentsRouteChildren: AssessmentsRouteChildren = {
  AssessmentsIdRoute: AssessmentsIdRoute,
  AssessmentsIndexRoute: AssessmentsIndexRoute,
}

const AssessmentsRouteWithChildren = AssessmentsRoute._addFileChildren(
  AssessmentsRouteChildren,
)

interface PreferencesRouteChildren {
  PreferencesIdRoute: typeof PreferencesIdRoute
  PreferencesIndexRoute: typeof PreferencesIndexRoute
}

const PreferencesRouteChildren: PreferencesRouteChildren = {
  PreferencesIdRoute: PreferencesIdRoute,
  PreferencesIndexRoute: PreferencesIndexRoute,
}

const PreferencesRouteWithChildren = PreferencesRoute._addFileChildren(
  PreferencesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessmentsRoute: AssessmentsRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PreferencesRoute: PreferencesRouteWithChildren,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
